[package]
name = "lattices"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
alloc = []
set = ["alloc"]

[dev-dependencies.blake3]
version = "1.0.0"
default-features = false

[dependencies.num]
version = "0.4.0"
default-features = false
