[package]
name = "lattices"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
std = ["blake3/std"]
alloc = []
btree = ["alloc"]
dag = ["blake3", "btree"]

[dependencies.blake3]
version = "1.0.0"
optional = true
default-features = false
features = ["digest", "crypto-mac"]
